# Generated by Django 6.0.2 on 2026-02-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_location_creator_alter_review_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="review_images/",
                verbose_name="Ảnh đính kèm",
            ),
        ),
    ]
