# Generated by Django 6.0.2 on 2026-02-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_review_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="location_images/",
                verbose_name="Ảnh địa điểm",
            ),
        ),
    ]
