# Generated by Django 6.0.2 on 2026-03-05 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_location_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_lat", models.FloatField(blank=True, null=True)),
                ("last_lon", models.FloatField(blank=True, null=True)),
                ("battery_level", models.IntegerField(default=100)),
                (
                    "status_message",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "friends",
                    models.ManyToManyField(blank=True, to="locations.userprofile"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
