# Generated by Django 6.0.2 on 2026-03-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
