# Generated by Django 6.0.2 on 2026-04-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_alter_location_creator_alter_location_geom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="close_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Giờ đóng cửa"),
        ),
        migrations.AddField(
            model_name="location",
            name="open_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Giờ mở cửa"),
        ),
    ]
