# Generated by Django 6.0.2 on 2026-04-01 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_location_close_time_location_open_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="location_images/",
                verbose_name="Ảnh đại diện",
            ),
        ),
        migrations.CreateModel(
            name="LocationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="location_gallery/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="locations.location",
                    ),
                ),
            ],
        ),
    ]
