# Generated by Django 6.0.2 on 2026-04-08 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "locations",
            "0012_userprofile_last_location_userprofile_status_message_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="locations.category",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="close_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="location_images/"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="location",
            name="open_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
