# Generated by Django 6.0.2 on 2026-05-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0013_alter_category_name_alter_location_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
