# Generated by Django 6.0.2 on 2026-05-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0014_userprofile_is_verified_userprofile_otp_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendrequest",
            name="is_active",
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="status",
            field=models.CharField(default="pending", max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="locations.userprofile"),
        ),
    ]
