# Generated by Django 6.0.2 on 2026-05-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "locations",
            "0015_remove_friendrequest_is_active_friendrequest_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="friends",
        ),
    ]
