# Generated by Django 6.0.2 on 2026-05-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0016_remove_userprofile_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="locations.userprofile"),
        ),
    ]
